const filePolicy = {
  "reset.css": "assets",
  "theme.js": "assets",
  "favicon.ico": "assets",
  "settings_data.json": "config",
  "theme.liquid": "layout",
  "password.liquid": "layout",
  "en.default.json": "locales",
  "contact-form.liquid": "sections",
  "featured-collection.liquid": "sections",
  "footer.liquid": "sections",
  "header.liquid": "sections",
  "store-name.liquid": "sections",
  "404.liquid": "sections",
  "article.liquid": "sections",
  "blog.liquid": "sections",
  "cart.liquid": "sections",
  "collection.liquid": "sections",
  "customer-login.liquid": "sections",
  "customer-register.liquid": "sections",
  "list-collections.liquid": "sections",
  "page.liquid": "sections",
  "product.liquid": "sections",
  "reset-password.liquid": "sections",
  "search.liquid": "sections",

  "meta-tags.liquid": "snippets",
  "pagination.liquid": "snippets",
  "product-card.liquid": "snippets",
  "product-media.liquid": "snippets",
  "404.json": "templates",
  "article.json": "templates",
  "blog.json": "templates",
  "cart.json": "templates",
  "collection.json": "templates",
  "index.json": "templates",
  "list-collections.json": "templates",
  "page.contact.json": "templates",
  "page.json": "templates",
  "product.json": "templates",
  "search.json": "templates",
  "login.json": "templates/customers",
  "register.json": "templates/customers",
  "reset_password.json": "templates/customers",
};

module.exports = { filePolicy };
